# These are supported funding model platforms

github: eljonny
patreon: jhyry87
open_collective: # Project was not approved.
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: jhyry87
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: jhyry87
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
